caret_analyze/plot/bokeh/callback_info.py

ament_flake8 が通るように修正させていただきました。

pass flake8 test

---

caret_analyze/plot/bokeh/callback_info.py

＜エラー原因＞
周波数をPlotするソースコードが「複数コールバックを持つノード」に対応していなかった。
＜修正内容＞
複数コールバックを持つノードに対応
＜結果＞
https://tier4.atlassian.net/browse/T4PB-16272
＜懸念点＞
pd.DataFrameの初期化をfor文の中に入れているため、処理速度に影響があるかもしれない。
（Hasegawaさんに相談済み。一旦これでマージし問題が発生するようであれば修正）

fix: modify frequency plot function

---

caret_analyze/plot/bokeh/callback_info_interface.py

@hsgwa 
お疲れ様です。
[こちらのチケット](https://tier4.atlassian.net/browse/T4PB-16679) に記載されている、「plot.show メソッドのY軸の縦スクロール対応」が完了したので、ご確認をお願いいたします。
y軸の縦スクロールのデフォルトは true としました。
テストコードとテストの結果を添付させていただきます。
- [テストコード](https://drive.google.com/file/d/1ajErrVe8Pz9-y9hxrStYNYoCRo6CiZ_A/view?usp=sharing)
- [出力された HTML](https://drive.google.com/file/d/190oKYX3Va97JW5khSpDTa1UyCpb1Jl7X/view?usp=sharing)

feat: y_axis_scroll

---

caret_analyze/infra/lttng/lttng.py

@hsgwa 
お疲れ様です。
トレースがロストしているかのチェックを lttng クラスに入れましたので、ご確認をお願いいたします。
以下はテストコードと、テスト実施結果です。
https://drive.google.com/drive/folders/1Xb2J-4rMiF07MStvQyq6fL_YtSs_v9Mv?usp=sharing

feat: check_for_traces_lost

---

caret_analyze/architecture/architecture.py
caret_analyze/architecture/graph_search.py
test/architecture/test_architecture.py
test/architecture/test_graph_search.py

feat: support search_path to intermediate nodes

---

caret_analyze/value_objects/path.py

fix: typo. closes #20

---

caret_analyze/infra/lttng/records_source.py

fix: add tid column name. closes #45

---

caret_analyze/infra/lttng/lttng_info.py
caret_analyze/infra/lttng/ros2_tracing/data_model.py
caret_analyze/infra/lttng/ros2_tracing/processor.py
caret_analyze/infra/lttng/value_objects/publisher.py

@hsgwa 
お疲れ様です。
rclcpp_publisher_init トレースポイントの読み込み及び、publisher 毎に rclcpp_publisher_init の有無を判定できる機能を実装しましたので、ご確認をお願いいたします。
cyclic_pipeline_intra_process における出力結果は以下です。
> WARNING : 2022-05-23 13:40:53 | caret-rclcpp is not used in the following publisher:
>         node name: /pipe1,
>         topic name: /rosout
> WARNING : 2022-05-23 13:40:53 | caret-rclcpp is not used in the following publisher:
>         node name: /pipe2,
>         topic name: /rosout

feat: check_caret_rclcpp_by_publisher

---

src/caret_analyze/plot/bokeh/callback_info_interface.py

@hsgwa 
[Legendの各プロットをクリックして、プロットを有効化/無効化できるようにしたい](https://tier4.atlassian.net/browse/T4PB-17399) が完了したのでご確認をお願いいたします。
出力されたグラフの凡例をクリックすることで、対応するプロットの表示・非表示ができます。
以下にテストコードによる結果を添付させていただきます。
- [テストコード(ipynb)](https://drive.google.com/file/d/1NpIVZb0oXsJ1hclmZKDCzAuo2U0GiMQ_/view?usp=sharing)
- [出力結果(HTML)](https://drive.google.com/file/d/1oc43P2wEIoG_rnqo95QA6GVe7p-uomln/view?usp=sharing)
- [使用したトレースデータ](https://drive.google.com/file/d/1GiyWDy67r1kYT7uRn2OgYiByllI129F5/view?usp=sharing)
- [使用したアーキテクチャファイル](https://drive.google.com/file/d/1B5qDvleWaQ5HyDyTnZ_5mXS1fu4TcsPn/view?usp=sharing)

feat: show and hide plots

---

src/caret_analyze/plot/__init__.py
src/caret_analyze/plot/bokeh/callback_info.py
src/caret_analyze/plot/bokeh/callback_info_factory.py
src/caret_analyze/plot/bokeh/callback_info_interface.py

@hsgwa 
コールバック粒度の実行周期・ジッタ・レイテンシの情報取得 API に関しての docstring を記載しました。
ご確認をお願いいたします。

docs: add docstring for API to get information per callback

---

.github/workflows/pytest.yaml

fix: add -y flag to apt-get install

---

.github/workflows/pytest.yaml
src/caret_analyze/infra/infra_base.py
src/caret_analyze/infra/lttng/architecture_reader_lttng.py
src/caret_analyze/infra/lttng/event_counter.py
src/caret_analyze/infra/lttng/lttng.py
src/test/infra/lttng/test_lttng.py

fix: lttng and architecture call order dependency. disable lttng singleton

---

src/caret_analyze/plot/bokeh/callback_sched.py

Fixing the problem of can only disappear a part of the graph of disabled legend.
But still can`t disappeared the arrow in the graph.

fix: fix the problem of can only disapper a part graph

---

src/caret_analyze/infra/lttng/lttng_info.py
src/caret_analyze/value_objects/node_path.py
src/test/infra/lttng/test_latency_definitions.py

This PR adds test codes for future refactoring.

test(lttng): add latency definition test

---

src/caret_analyze/record/record_cpp_impl.py
src/package.xml

This PR is a patch to match with this diff : https://github.com/tier4/CARET_analyze_cpp_impl/pull/17

chore(records_cpp): change export_json to export_yaml

---

src/caret_analyze/plot/bokeh/callback_sched.py

add docstring for Callback Scheduling Visualization
Signed-off-by: Bo Peng <82485734+bopeng-saitama@users.noreply.github.com>

docs: add docstring for Callback Scheduling Visualization

---

src/caret_analyze/plot/bokeh/message_flow.py

This patch modify timestamp style inside tooltip as below.
```
t_start = 4.470 [s]
t_end = 4.673 [s]
latency = 202.679 [ms]
t_offset = 2022-05-17 18:09:06
```
Used data: [fix_message_flow_time_style.zip](https://github.com/tier4/CARET_analyze/files/9174169/fix_message_flow_time_style.zip)

fix: time stamp style for message flow

---

src/caret_analyze/plot/bokeh/callback_info_interface.py

@hsgwa @takam5f2  CC: @keita1523 
[plt.show() のコールバック数が11以上になると、Legendで表示できない問題の対策](https://tier4.atlassian.net/browse/T4PB-19007) の作業が完了したので、ご確認をお願いいたします。
以下は再現に必要なファイルです。
- [テストコード1](https://drive.google.com/file/d/1GWjhdUQHjwHiBvE-OxODhnYZnz2KdQBy/view?usp=sharing)
-  [出力結果](https://drive.google.com/file/d/1SFZjj0QN6rNyEMu-3ktT8DHWOcc2sWfe/view?usp=sharing)
- [テストコード2](https://drive.google.com/file/d/1k4D25CXKkoZmVR_Uwzg__Cndv_QTEQ9T/view?usp=sharing)
- [出力結果](https://drive.google.com/file/d/1aMuMQ8B4DTxJ80YN6qbBbaQcYk5UNM42/view?usp=sharing)
- [使用したトレースデータ](https://drive.google.com/file/d/1hALgv-iwjy54nJ_M_W3f0Kgkvc0OlEEx/view?usp=sharing)
- [使用したアーキテクチャファイル](https://drive.google.com/file/d/1dRInIE2HquYziQ-qLakVL3_nAyrUMeh5/view?usp=sharing)

feat: display legends by 10 and add full_legends option in plot.show()

---

.github/sync-files.yaml
.github/workflows/deploy-docs.yaml

Signed-off-by: Takayuki AKAMINE <takayuki.akamine@tier4.jp>

fix(deploy-doc): add new trigger to invoke deploy-docs

---

src/caret_analyze/record/response_time.py

docs(response_time): modify example

---

src/caret_analyze/record/record_cpp_impl.py

docs(record_cpp): add warnings section for records.data

---

src/caret_analyze/plot/__init__.py
src/caret_analyze/plot/bokeh/callback_info.py
src/caret_analyze/plot/bokeh/callback_info_interface.py
src/caret_analyze/plot/bokeh/callback_sched.py
src/caret_analyze/plot/bokeh/communication_info.py
src/caret_analyze/plot/bokeh/communication_info_interface.py
src/caret_analyze/plot/bokeh/plot_factory.py
src/caret_analyze/plot/bokeh/plot_util.py
src/caret_analyze/plot/bokeh/pub_sub_info.py
src/caret_analyze/plot/bokeh/pub_sub_info_interface.py
src/caret_analyze/plot/bokeh/util.py
src/caret_analyze/runtime/application.py
src/caret_analyze/value_objects/communication.py

[トピックの通信のレイテンシ、送信/受信周期、通信間隔の描画をサポートする](https://tier4.atlassian.net/browse/T4PB-19177) チケットの作業を行っています。

feat: add API to plot topic_info

---

src/caret_analyze/infra/lttng/lttng.py
src/test/infra/lttng/test_lttng.py

This patch adds missing implementation of #117

fix(lttng): missing implementation of #117

---

src/test/infra/lttng/test_event_counter.py

#121  was overlooking pytest error.
This patch fixes its error to pass all tests.

test(lttng): pass event_counter tests

---

src/caret_analyze/plot/bokeh/callback_info_interface.py

The original changes are PR #109, but some changes were accidentally removed at PR #108

fix: change plot APIs to return figure object

---

src/caret_analyze/plot/bokeh/communication_info.py
src/caret_analyze/plot/bokeh/communication_info_interface.py
src/caret_analyze/plot/bokeh/pub_sub_info_interface.py

docs(plot): add todo

---

src/caret_analyze/infra/lttng/records_provider_lttng.py
src/caret_analyze/infra/lttng/records_source.py
src/caret_analyze/record/__init__.py
src/caret_analyze/record/interface.py
src/caret_analyze/record/record.py
src/caret_analyze/record/record_cpp_impl.py
src/caret_analyze/runtime/path.py
src/test/record/test_record.py

Signed-off-by: Bo Peng <82485734+bopeng-saitama@users.noreply.github.com>
fix typo error (sequencial-> sequential)

fix(word): typo error

---

src/caret_analyze/plot/bokeh/communication_info.py
src/caret_analyze/plot/bokeh/communication_info_interface.py
src/caret_analyze/plot/bokeh/pub_sub_info.py
src/caret_analyze/plot/bokeh/pub_sub_info_interface.py
src/test/plot/bokeh/test_pub_sub_info_interface.py

This PR corrects TODO that was added in https://github.com/tier4/CARET_analyze/pull/131.

fix(plot): fix todo comment in Plot

---

src/caret_analyze/plot/bokeh/pub_sub_info_interface.py

This PR commented out the `interactive` option of show() in PubSubXXXPlot.

chore(plot): comment out interactive option

---

src/caret_analyze/plot/bokeh/callback_info.py
src/caret_analyze/plot/bokeh/callback_info_interface.py
src/caret_analyze/plot/bokeh/communication_info.py
src/caret_analyze/plot/bokeh/communication_info_interface.py
src/caret_analyze/plot/bokeh/pub_sub_info.py
src/caret_analyze/plot/bokeh/pub_sub_info_interface.py

@hsgwa 
This PR adds error handling if the size of DataFrame obtained by the to_dataframe() method is 0.
https://emb4hq.slack.com/archives/C017YM4AA06/p1662622513491059?thread_ts=1659948870.138049&cid=C017YM4AA06
To Reproduce: https://drive.google.com/drive/folders/1qtM778Ob7Chv-XAUuaOfUucKosDMCTyd?usp=sharing

fix(plot): add error handling for to_dataframe() if size 0

---

src/caret_analyze/plot/bokeh/pub_sub_info_interface.py

This changed the tooltip in pubsubTimeSeriesPlot.show() to the node/topic name.
To reproduce: https://drive.google.com/drive/folders/1qtM778Ob7Chv-XAUuaOfUucKosDMCTyd?usp=sharing

fix(plot): fix tooltip in pubsubTimeSeriesPlot.show() to node/topic name

---

src/caret_analyze/architecture/architecture_exporter.py
src/caret_analyze/common/singleton.py
src/caret_analyze/infra/lttng/event_counter.py
src/caret_analyze/infra/lttng/lttng_info.py
src/caret_analyze/infra/lttng/records_provider_lttng.py
src/caret_analyze/infra/lttng/records_source.py
src/caret_analyze/infra/yaml/architecture_reader_yaml.py
src/caret_analyze/plot/bokeh/callback_sched.py
src/caret_analyze/plot/bokeh/message_flow.py
src/caret_analyze/record/interface.py
src/caret_analyze/record/record.py
src/caret_analyze/runtime/application.py
src/caret_analyze/runtime/executor.py
src/caret_analyze/runtime/runtime_loaded.py
src/test/architecture/test_architecture_loader.py
src/test/infra/lttng/test_architecture_reader_lttng.py
src/test/infra/lttng/test_latency_definitions.py
src/test/infra/yaml/test_yaml.py
src/test/runtime/test_runtime_data_assigned.py

Signed-off-by: Bo Peng <82485734+bopeng-saitama@users.noreply.github.com>
Change local variable names / comment to fix the spell check error.
Changed word:
- byld -> by_ld
- timerstamp -> time_stamp
- keyname -> key_name 
- strct -> struct
- rects -> rect_list
- cbgs -> callback_groups 
- addrs -> addresses 
- lttngs -> lttng_list  
- ctrl -> control
- ctrls -> controls 
- maxs -> max_list 
- kargs -> kwargs

chore: change local variable names

---

src/caret_analyze/infra/lttng/event_counter.py

fix: typo in validation error message

---

src/caret_analyze/infra/lttng/lttng.py
src/caret_analyze/infra/lttng/records_provider_lttng.py
src/caret_analyze/record/interface.py
src/caret_analyze/runtime/path_base.py

This PR prettify CARET API document.
- https://tier4.github.io/CARET_analyze/pr-152/infra/#caret_analyze.infra.lttng.records_provider_lttng.RecordsProviderLttng.callback_records
- https://tier4.github.io/CARET_analyze/pr-152/record/#caret_analyze.record.interface.RecordsInterface.merge

docs: prettify api document

---

src/caret_analyze/plot/bokeh/message_flow.py

This PR fixes an error during "message_flow with use_sim_time=True".

fix: message_flow assert with use_sim_time=True

---

src/caret_analyze/__init__.py
src/caret_analyze/infra/lttng/__init__.py
src/caret_analyze/infra/lttng/lttng.py
src/caret_analyze/infra/lttng/lttng_event_filter.py
src/caret_analyze/record/record.py

chore: move LttngEventFilter to lttng_event_filter.py

---

src/caret_analyze/plot/bokeh/callback_info.py
src/caret_analyze/plot/bokeh/callback_info_interface.py
src/caret_analyze/plot/bokeh/communication_info.py
src/caret_analyze/plot/bokeh/communication_info_interface.py
src/caret_analyze/plot/bokeh/plot_factory.py
src/caret_analyze/plot/bokeh/pub_sub_info.py
src/caret_analyze/plot/bokeh/pub_sub_info_interface.py

This PR unifies the interface of the time series data plotting API to `Collection[TARGET_OBJECT]`.
To reproduce: https://drive.google.com/drive/folders/1Egu_tpNeU_KyC7BMa___a-6eKnPr5dAd?usp=sharing

refactor(plot): unify interface of time-series plot API to Collection[XXX]

---

src/caret_analyze/infra/lttng/lttng_info.py

This PR fixes oversights of the following PR.
https://github.com/tier4/CARET_analyze/pull/115

fix(lttng_info): value error in pandas merge "merge on object and float64 columns"

---

src/caret_analyze/record/frequency.py
src/caret_analyze/record/latency.py
src/caret_analyze/record/response_time.py
src/caret_analyze/runtime/application.py
src/caret_analyze/runtime/callback.py
src/caret_analyze/runtime/callback_group.py
src/caret_analyze/runtime/communication.py
src/caret_analyze/runtime/executor.py
src/caret_analyze/runtime/node.py
src/caret_analyze/runtime/node_path.py
src/caret_analyze/runtime/path.py
src/caret_analyze/runtime/publisher.py
src/caret_analyze/runtime/subscription.py
src/caret_analyze/runtime/timer.py
src/caret_analyze/runtime/variable_passing.py

Adapt humble flake8.
Signed-off-by: keita1523 <keita.miura@tier4.jp>

test: adapt humble flake8

---

.github/sync-files.yaml

Signed-off-by: Takayuki AKAMINE <takayuki.akamine@tier4.jp>

ci: add sd pre-command to ignore deletion of mkdocs-reuqirements-txt

---

src/caret_analyze/architecture/architecture.py

This PR set a default value of `max_node_depth` and add messages in `Architecture.search_paths()`
- JIRA ticket: https://tier4.atlassian.net/browse/T4PB-20205
- To reproduce: https://drive.google.com/drive/folders/1Qd3BprOFOVDHp3b0_1Sf9snEFfcJzL4W?usp=share_link

chore: set max_node_depth default and add messages in search_paths

---

.github/workflows/pytest.yaml
src/caret_analyze/__init__.py

This PR bumps up pytest environment from galactic@ubuntu20.04 to humble@ubuntu22.04

chore(github):  modify pytest from galactic to humble

---

src/caret_analyze/architecture/architecture.py

It seems both following PRs add properties.
- https://github.com/tier4/CARET_analyze/pull/179
- https://github.com/tier4/CARET_analyze/pull/199

chore: remove duplicated publishers and subscriptions

---

src/caret_analyze/common/clock_converter.py
src/caret_analyze/plot/bokeh/callback_info.py
src/caret_analyze/plot/bokeh/communication_info.py
src/caret_analyze/plot/bokeh/communication_info_interface.py
src/caret_analyze/plot/bokeh/plot_util.py
src/caret_analyze/plot/bokeh/pub_sub_info.py
src/caret_analyze/record/frequency.py
src/test/record/test_frequency.py

This PR fixes a bug of frequency_plot that the start time of the frequency_plot was misaligned with the correct start time.
JIRA ticket: https://tier4.atlassian.net/browse/T4PB-23472

fix(plot): bug in frequency plot start time is out of alignment

---

src/caret_analyze/__init__.py
src/caret_analyze/exceptions.py
src/caret_analyze/value_objects/__init__.py
src/caret_analyze/value_objects/callback.py
src/caret_analyze/value_objects/callback_group.py
src/caret_analyze/value_objects/node.py
src/caret_analyze/value_objects/node_path.py
src/caret_analyze/value_objects/qos.py
src/caret_analyze/value_objects/value_object.py

docs(exceptions,value_objects): add docstring

---

src/caret_analyze/architecture/architecture.py
src/caret_analyze/architecture/architecture_loaded.py
src/caret_analyze/architecture/graph_search.py
src/caret_analyze/architecture/struct/callback.py
src/caret_analyze/architecture/struct/callback_group.py
src/caret_analyze/architecture/struct/communication.py
src/caret_analyze/architecture/struct/executor.py
src/caret_analyze/architecture/struct/message_context.py
src/caret_analyze/architecture/struct/node.py
src/caret_analyze/architecture/struct/node_path.py
src/caret_analyze/architecture/struct/path.py
src/caret_analyze/architecture/struct/publisher.py
src/caret_analyze/architecture/struct/subscription.py
src/caret_analyze/architecture/struct/timer.py
src/caret_analyze/architecture/struct/variable_passing.py
src/test/architecture/test_architecture.py
src/test/architecture/test_architecture_loader.py

`Architecture.renameXXX` functions are implemented in this PR.
Signed-off-by: rokamu623 <r.okamura.061@ms.saitama-u.ac.jp>

feat: rename function

---

src/caret_analyze/plot/visualize_lib/bokeh.py

this PR to add legend label to tooltips as the following picture shows.
This PR is altenative of #218 

chore(plot): add legend label to tooltips

---

src/caret_analyze/plot/visualize_lib/bokeh.py

This PR fixes an error that occurs in create_publish_subscription_frequency_plot or create_publish_subscription_period_plot
https://tier4.atlassian.net/browse/T4PB-24701

fix(plot): fix ValueError in create_publish_subscription_frequency_plot

---

src/caret_analyze/infra/lttng/ros2_tracing/data_model_service.py

This PR removes assertion for duplicated node handlers, and add warning message.
https://tier4.atlassian.net/browse/T4PB-24856

fix(lttng): modify assertion to warning message for duplicated node handlers

---

src/caret_analyze/infra/lttng/lttng_info.py

This PR suppress following warnings.
```
WARNING : 2023-01-11 20:19:56 | Failed to load node. node_name = /control/trajectory_follower/lane_departure_checker_node, duplicated callback id. node_id: /control/trajectory_follower/lane_departure_checker_node_94431941000736
node_name: /control/trajectory_follower/lane_departure_checker_node
, callback_group_id: callback_group_140413688160736
callback_group_name: null
callback_group_type:
type_name: mutually_exclusive
callback_ids:
- timer_callback_94431943022880
- timer_callback_94431943022880
- timer_callback_140413688581024
- subscription_callback_94431944044472
- subscription_callback_94431944131096
- subscription_callback_94431944094968
- subscription_callback_94431944137464 …
```

fix: suppress warnings with duplicated callback id 

---

src/caret_analyze/architecture/architecture_loaded.py
src/caret_analyze/architecture/struct/variable_passing.py
src/caret_analyze/infra/lttng/architecture_reader_lttng.py
src/caret_analyze/infra/lttng/bridge.py
src/caret_analyze/infra/lttng/lttng.py
src/caret_analyze/infra/lttng/ros2_tracing/processor.py
src/caret_analyze/record/column.py
src/caret_analyze/runtime/path_base.py
src/caret_analyze/value_objects/variable_passing.py

Currently, checks by mypy have been introduced and there is an unnecessary ASSERT.
The assert will be a fatal error in the future, so it has been reviewed.
- Delete unnecessary asserts
- Add comments for asserts.
- Fixed bugs found.

fix: remove excessive assert and correct identation of assert

---

src/caret_analyze/infra/lttng/lttng_info.py

This PR uses lru_cache to refactor existing code
It is easier to read if you review each commit.

refactor(lttng_info): remove redundant member variables

---

src/caret_analyze/infra/lttng/lttng.py

- I'm developing a GUI tool to control CARET ( `record` , `check_ctf` , etc.)
- It works fine in a normal environment like my PC. However, I need to control CARET in a remote PC from a local PC, as well.
- To control CARET in a remote PC, I use `pexpect` library and connect the remote PC via ssh
- However, when I run `check_ctf` via ssh using `pexpect` , lttng convert takes very long time (x2~5 compared to the time when I manually login the remote PC via ssh and manually run `check_ctf` in a terminal )
- I found that it's because that display update by `tqdm` is too frequent (0.1 sec by default)
- So, I'd like to make it 1.0 sec. It will be enough to check progress and I confirmed lttng convert keeps expected speed.
I also …

chore(lttng): enlarge interval of tqdm.

---

src/caret_analyze/infra/lttng/event_counter.py

Signed-off-by: yamasaki <114902604+ymski@users.noreply.github.com>
This PR fixes the following behaviour.
1. measurement by caret during application execution.
2. verification of trace data by ros2 caret check_ctf
ros2 caret check_ctf outputs a "Failed to find trace point added by caret-rclcpp" warning for trace data from applications built without using caret. However, even for applications built without caret, the warning was not issued for trace data with the above conditions.
After investigation, it was found that `ros2 caret check_ctf` could not be performed properly after https://github.com/tier4/ros2caret/pull/48 was merged. The cause of the data validation not working correctly was the `caret/start_record` and `caret/end_record` topics published from outside the target application …

fix(lttng): exclude caret_record topics

---

src/caret_analyze/architecture/architecture.py

Signed-off-by: rokamu623 <r.okamura.061@ms.saitama-u.ac.jp>
add docstring for Architecture::rename_XXX function
https://github.com/tier4/CARET_analyze/pull/156

docs: documentation of rename_XXX

---

src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
src/caret_analyze/record/__init__.py
src/caret_analyze/record/records_service/__init__.py
src/caret_analyze/record/records_service/range.py
src/test/record/records_service/test_range.py

This PR moves Bokeh.get_range() function to the records package.
I have confirmed that there are no regressions using CARET_report.

refactor(plot): move Bokeh.get_range() to record package

---

src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py

This PR improves readability of _apply_x_axis_offset().

refactor(plot): improve readability of _apply_x_axis_offset()

---

src/caret_analyze/plot/visualize_lib/bokeh/callback_scheduling_source.py
src/caret_analyze/plot/visualize_lib/bokeh/legend.py
src/caret_analyze/plot/visualize_lib/bokeh/timeseries_source.py

Rename class name and related words because it's wrong.

chore: rename class name

---

src/caret_analyze/plot/plot_facade.py
src/caret_analyze/plot/stacked_bar/__init__.py
src/caret_analyze/plot/stacked_bar/latency_stacked_bar.py
src/caret_analyze/plot/stacked_bar/stacked_bar_plot.py
src/caret_analyze/plot/stacked_bar/stacked_bar_plot_factory.py
src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
src/caret_analyze/plot/visualize_lib/bokeh/legend.py
src/caret_analyze/plot/visualize_lib/bokeh/stacked_bar_source.py
src/caret_analyze/plot/visualize_lib/visualize_lib_interface.py
src/test/plot/stacked_bar/test_latency_stacked_bar.py

Bokeh and Plot packages for stacked bar graph.
To run or check pytest, lease merge this PR.
https://github.com/tier4/CARET_analyze/pull/259

feat: bokeh and plot packages for stacked bar

---

src/caret_analyze/plot/visualize_lib/bokeh/callback_scheduling_source.py
src/caret_analyze/plot/visualize_lib/bokeh/message_flow_source.py
src/caret_analyze/plot/visualize_lib/bokeh/stacked_bar_source.py
src/caret_analyze/plot/visualize_lib/bokeh/timeseries_source.py
src/caret_analyze/plot/visualize_lib/bokeh/util/__init__.py
src/caret_analyze/plot/visualize_lib/bokeh/util/hover.py

This PR refactors hover.py in plot package.
To reproduce:
- [ipynb](https://drive.google.com/drive/folders/1k7SliaXZeguHYcqMXPr2wmK-C0qrucOw?usp=share_link)
- [archtecture file](https://drive.google.com/file/d/1W9PDyj046xzapMA-p3o6HWtUhMA8JhIG/view?usp=share_link)
- [trace data](https://drive.google.com/file/d/1xy1L4c-eGi9RSHog1qNgovTcwxoM74Z9/view?usp=share_link)
I have confirmed that there are no regressions using CARET_report.

refactor(plot): refactor hover in plot package

---

src/caret_analyze/plot/plot_base.py
src/caret_analyze/plot/plot_facade.py

This PR adds docstrings for plot package.
- JIRA ticket: https://tier4.atlassian.net/browse/RT2-627

docs(plot): add docstring for plot package

---

src/caret_analyze/plot/plot_facade.py

This PR disables `singledispatchmethod` library in plot_facade.py.
- Discussion: https://tier4.atlassian.net/browse/RT2-713?focusedCommentId=122819
- To reproduce: 
- [ipynb, html](https://drive.google.com/drive/folders/1rqbZhhfK1Q_kv7D5AXBza_3D_84lZQkT?usp=share_link)
- [trace data](https://drive.google.com/file/d/1xy1L4c-eGi9RSHog1qNgovTcwxoM74Z9/view?usp=share_link)
- [architecture file](https://drive.google.com/file/d/1W9PDyj046xzapMA-p3o6HWtUhMA8JhIG/view?usp=share_link)
There is no degradation using CARET_report.

fix(plot): disable singledispatchmethod in plot_facade

---

.pre-commit-config.yaml
src/caret_analyze/architecture/architecture.py
src/caret_analyze/architecture/struct/callback.py
src/caret_analyze/architecture/struct/node.py
src/caret_analyze/architecture/struct/publisher.py
src/test/architecture/test_architecture.py

Implement the `remove_XXX` function.
These remove data paths defined by the user.
Jira: https://tier4.atlassian.net/browse/RT2-389
CARET_doc: https://tier4.github.io/CARET_doc/latest/configuration/intra_node_data_path/
ipynb: https://drive.google.com/file/d/1FOme9ao5oUEM7SrrpGMSWwg6hMdZVXWt/view?usp=drive_link
　yaml: https://drive.google.com/file/d/1iKZlExzQghfGGRyJC-mR_KjPTMhPJ_Jw/view?usp=drive_link

feat: remove function

---

src/test/record/test_record.py

This PR fixes words to pass pytest.

fix: fix words to pass pytest

---

src/caret_analyze/plot/visualize_lib/bokeh/stacked_bar.py

In graphs generated by `Plot.create_response_time_stacked_bar_plot()` the ability to make the drawing of certain callbacks semi-transparent is not working correctly.
Refactoring of `caret_analyze/plot/visualize_lib/bokeh/stacked_bar.py` was done in association with the resolution of this issue.
Jira: https://tier4.atlassian.net/browse/RT2-806
Test scripit: [Jira->説明->path.zip](https://tier4.atlassian.net/browse/RT2-806)
Github(see also):
https://github.com/tier4/CARET_analyze/pull/265/files
- Implementation of stacked bar plot
https://github.com/tier4/CARET_analyze/pull/287/files
- Implementation of separate hover for each bar.
- However, a transparency issue occurred here.
- Does hover move correctly?
- Does the click policy (transparency) work correctly?
regression test of CARET_report …

fix: stack bar transparent and refactor stacked bar

---

src/caret_analyze/infra/lttng/event_counter.py
src/caret_analyze/infra/lttng/records_source.py
src/caret_analyze/infra/lttng/ros2_tracing/processor.py
src/test/infra/lttng/test_event_counter.py
src/test/infra/lttng/test_latency_definitions.py

Currently CARET and ros2-tracing have different definitions of rclcpp_publish trace points.
- the tracepoint definition
- [CARET](https://github.com/tier4/ros2_tracing/blob/master/tracetools/include/tracetools/tp_call.h)
- [ros2-tracing](https://github.com/ros2/ros2_tracing/blob/rolling/tracetools/include/tracetools/tp_call.h)
In order to perform measurements without using [caret-rclcpp](https://github.com/tier4/rclcpp/tree/humble_tracepoint_added), it is necessary to make modifications to read the trace data to absorb the differences caused by the above tracepoint definitions.
The method of obtaining the publisher_handle in linking the publish_records needs to be changed according to the definition of the trace point in ros2-tracing. …

feat: changes to the method of obtaining publisher_handle information

---

mkdocs-requirements.txt

This PR corrects an error that has been occurring since early Augut in `deploy-docs` action.

chore: fix error occured in deploy-docs action

---

src/caret_analyze/common/progress.py
src/caret_analyze/infra/lttng/records_provider_lttng.py
src/caret_analyze/infra/lttng/records_source.py
src/caret_analyze/record/interface.py
src/caret_analyze/record/record.py
src/caret_analyze/record/record_cpp_impl.py
src/caret_analyze/runtime/path.py

- Interface changed with removal of unnecessary dependencies
- Progress bar was not used in the current CARET
- https://github.com/tier4/CARET_analyze_cpp_impl/pull/142

feat: remove progress_bar

---

src/caret_analyze/plot/histogram/histogram_plot.py
src/caret_analyze/plot/histogram/histogram_plot_factory.py
src/caret_analyze/plot/plot_facade.py
src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
src/caret_analyze/plot/visualize_lib/bokeh/util/legend.py
src/caret_analyze/plot/visualize_lib/visualize_lib_interface.py

- Update `bokeh.histogram()` to implement histogram of response time.
- Delete implementation of 'best-to-worst' option which is no longer in use.
Jira: https://tier4.atlassian.net/browse/RT2-862

feat: response time histogram

---

src/requirements.txt

There are implementations in CARET that are not compatible with multimethod v1.10.
Therefore, the version is fixed to less than v1.10.

fix: multimethod temporary fix

---

src/caret_analyze/infra/lttng/column_names.py
src/caret_analyze/infra/lttng/event_counter.py
src/caret_analyze/infra/lttng/lttng.py
src/caret_analyze/infra/lttng/lttng_info.py
src/caret_analyze/infra/lttng/records_source.py
src/caret_analyze/infra/lttng/ros2_tracing/data_model.py
src/caret_analyze/infra/lttng/ros2_tracing/processor.py
src/test/infra/lttng/ros2_tracing/test_ros2_tracing.py
src/test/infra/lttng/test_event_counter.py
src/test/infra/lttng/test_latency_definitions.py
src/test/infra/lttng/test_lttng_info.py

This PR will implement the following contents:
- Method to read newly added trace points
- Script to analyze newly added trace points
- We can continue to analyze trace points for humble as well as iron.
The trace points added in iron are the following:
- ros2:ring_buffer_construct
- ros2:ring_buffer_enqueue  (runtime)
- ros2:ring_buffer_dequeue  (runtime)
- ros2:ring_buffer_clear
- ros2:buffer_to_ipb
- ros2:ipb_to_subscription
In addition, the following existing tracepoints have been modified for
- ros2_caret:caret_init
- added ros distribution (str)
- When analyzing trace data (=old data), which has no distribution information, the distribution is treated as the value `NOTFOUND`.
- https://github.com/tier4/CARET_trace/pull/150
The PR reviewers **must** check the checkboxes below before …

feat: support iron useful tracepoints

---

src/caret_analyze/record/record_factory.py
src/caret_analyze/record/records_service/frequency.py
src/caret_analyze/record/records_service/latency.py
src/caret_analyze/record/records_service/period.py
src/caret_analyze/record/records_service/response_time.py
src/caret_analyze/record/records_service/stacked_bar.py
src/requirements.txt
src/test/plot/stacked_bar/test_latency_stacked_bar.py
src/test/record/records_service/test_stacked_bar.py

support for multimethod 1.10.
Jira: https://tier4.atlassian.net/browse/RT2-984

fix: support for multimethod 1.10

---

src/caret_analyze/infra/lttng/records_provider_lttng.py
src/caret_analyze/infra/lttng/records_source.py
src/caret_analyze/infra/lttng/ros2_tracing/data_model.py
src/caret_analyze/plot/metrics_base.py
src/caret_analyze/record/records_service/response_time.py
src/caret_analyze/record/records_service/stacked_bar.py

An error has occurred due to `RecordsFactory.create_instance`.
This error was resolved by explicitly specifying `column=` as the second argument of `RecordsFactory.create_instance`.

fix: error of RecordsFactory.create_instance

---

src/caret_analyze/plot/callback_scheduling/callback_scheduling_plot.py
src/caret_analyze/plot/histogram/histogram.py
src/caret_analyze/plot/histogram/histogram_plot.py
src/caret_analyze/plot/message_flow/message_flow_plot.py
src/caret_analyze/plot/plot_base.py
src/caret_analyze/plot/stacked_bar/stacked_bar_plot.py
src/caret_analyze/plot/timeseries/timeseries_plot.py
src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
src/caret_analyze/plot/visualize_lib/bokeh/callback_scheduling.py
src/caret_analyze/plot/visualize_lib/bokeh/message_flow.py
src/caret_analyze/plot/visualize_lib/bokeh/response_time_hist.py
src/caret_analyze/plot/visualize_lib/bokeh/stacked_bar.py
src/caret_analyze/plot/visualize_lib/bokeh/timeseries.py
src/caret_analyze/plot/visualize_lib/bokeh/util/legend.py
src/caret_analyze/plot/visualize_lib/bokeh/util/util.py
src/caret_analyze/plot/visualize_lib/visualize_lib_interface.py
src/requirements.txt

support for bokeh version 2.x (3.3.0 latest).
the solution to one mypy error is debatable.
Jira: https://tier4.atlassian.net/browse/RT2-792

fix: support for bokeh 3.x

---

src/package.xml

the libraries that caret depends on are installed by ansible. To add caret to buildfarm, we put dependency library in package.xml

feat: change xml for buildfarm

---

src/caret_analyze/common/util.py
src/caret_analyze/infra/lttng/lttng.py
src/caret_analyze/record/interface.py
src/caret_analyze/record/records_service/response_time.py
src/caret_analyze/runtime/application.py
src/caret_analyze/runtime/callback_group.py

fix: revision doc_string

---

src/package.xml

Because there was no upgrade in package.xml version tag, update to 0.4.22 for rosdistro review.

chore: update xml version

---

src/caret_analyze/infra/lttng/event_counter.py
src/caret_analyze/infra/lttng/records_source.py

Determination method of ROS distribution for iron or rolling replaces to correspond to distribution after iron.

refactor: improvement of determination ros distribution

---

src/package.xml

chore: package.xml version to 0.4.24

---

src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py

A problem with the histogram terminating in error when an empty Records is inputted has been resolved.
After the resolve, an empty histogram is displayed.
Jira: https://tier4.atlassian.net/browse/RT2-1202

fix: error with empty records

---

.github/workflows/update-caret-version.yaml

Until now, no update have been included in packege.xml version.
Added workflow to update the version of package.xml to match the tag when a tag is pushed.

feat: workflow file for auto update package.xml

---

src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
src/caret_analyze/plot/visualize_lib/bokeh/util/legend.py

fix: histogram improvement

---

.github/workflows/pytest.yaml

Update container image for pytest.

chore: update pytest job

---

src/caret_analyze/common/type_check_decorator.py

If pydantic is not installed or is not the latest version, warn `UserWarning`.
Jira: https://tier4.atlassian.net/browse/RT2-1442

feat: warning without import pydantic in `type_check_decorator`

---

src/caret_analyze/plot/histogram/histogram_plot.py
src/caret_analyze/plot/histogram/histogram_plot_factory.py
src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
src/caret_analyze/plot/visualize_lib/visualize_lib_interface.py

Refactoring of the code related to `histograms` is conducted.
The contents are mainly categorized as follows:
- Removal of redundant code [#1a73809](https://github.com/tier4/caret_analyze/pull/481/commits/1a7380932817fb9e6a39ab2a7f8f417cd3094a33)
- Moving the codes calculating the data (hist, bins) to draw histograms, from `bokeh` (drawing class) to `HistogramPlot` (histogram class) [#21431d1](https://github.com/tier4/caret_analyze/pull/481/commits/21431d1d448494102397dcb03cc39f9da14c2ce5)
- Implement a wrapper function that return both `to_records()` and `to_xxx_records()` properly, to reduce the code for the calculation part [#d65806d](https://github.com/tier4/caret_analyze/pull/481/commits/d65806d8b6bf3741f52a276fc430c7c17377fa0f)
- Changed variable names to match the actual of the …

refactor: histogram to data calculation from `bokeh` to `HistogramPlot`

---

src/caret_analyze/architecture/architecture_loaded.py

Remove duplicated code.
[](https://tier4.atlassian.net/browse/RT2-1501)

fix: remove duplicated code for service callback

---

src/caret_analyze/infra/lttng/lttng.py

Provide a filter function suitable for analyzing multiple data.
[Tier4 INTERNAL LINK](https://tier4.atlassian.net/browse/RT2-1429)

feat: update EventFilter for multiple data loading

---

src/caret_analyze/architecture/architecture_loaded.py

changed the log level for Failed to load executor
https://tier4.atlassian.net/browse/RT2-1614

fix: changed the log level for Failed to load executor

---

src/caret_analyze/architecture/architecture.py
src/caret_analyze/architecture/architecture_exporter.py
src/caret_analyze/architecture/architecture_loaded.py
src/caret_analyze/common/clock_converter.py
src/caret_analyze/common/summary.py
src/caret_analyze/common/type_check_decorator.py
src/caret_analyze/common/util.py
src/caret_analyze/infra/lttng/architecture_reader_lttng.py
src/caret_analyze/infra/lttng/lttng.py
src/caret_analyze/infra/lttng/records_provider_lttng.py
src/caret_analyze/record/record_cpp_impl.py
src/caret_analyze/runtime/application.py
src/caret_analyze/runtime/path_base.py
src/caret_analyze/value_objects/value_object.py
src/test/architecture/test_architecture.py
src/test/architecture/test_architecture_loader.py
src/test/common/test_logger_config.py
src/test/infra/lttng/test_architecture_reader_lttng.py
src/test/infra/lttng/test_latency_definitions.py
src/test/infra/lttng/test_lttng.py
src/test/infra/lttng/test_records_provider_lttng.py
src/test/runtime/test_application.py
src/test/value_objects/test_value_object.py

Reviewed import statements other than the beginning of caret_analyze
https://tier4.atlassian.net/browse/RT2-1525

fix: reviewed import statements

---

.github/workflows/pytest.yaml

chore: update docker image

---

src/caret_analyze/infra/lttng/event_counter.py
src/test/infra/lttng/test_event_counter.py

Tracepoints may not be collected correctly due to hidden function symbols in the dds layer. Added a function to verify if these are collected correctly.
[TIERⅣ Internal Link](https://tier4.atlassian.net/browse/RT2-1711)

feat: validate dds tracepoint

---

src/requirements.txt

Several issues have been raised by the new version of mypy on github actions. We will operate github actions by restricting the version for the time until we can examine the validity of these new issues.
[TIER4 INTERNAL LINK](https://tier4.atlassian.net/browse/RT2-1752)

chore: restricted to mypy version

---

src/caret_analyze/infra/lttng/records_provider_lttng.py
src/caret_analyze/infra/lttng/ros2_tracing/data_model_service.py
src/caret_analyze/runtime/path.py
src/test/infra/lttng/test_records_provider_lttng.py
src/test/runtime/test_path.py

Refactoring and minor fixes related to this PR https://github.com/tier4/caret_analyze/pull/516

refactor: refactoring for the case of merging with source timestamp

---

src/caret_analyze/plot/stacked_bar/latency_stacked_bar.py
src/caret_analyze/plot/visualize_lib/bokeh/stacked_bar.py
src/caret_analyze/record/interface.py
src/caret_analyze/record/records_service/response_time.py
src/caret_analyze/record/records_service/stacked_bar.py
src/test/plot/stacked_bar/test_latency_stacked_bar.py
src/test/record/records_service/test_response_time.py
src/test/record/records_service/test_stacked_bar.py

Fixed StackedBar when time reversal occurs
https://tier4.atlassian.net/browse/RT2-1586

fix: fixed stackedbar when time reversal occurs

---

src/package.xml

This pull request updates the version in package.xml to v0.5.14

chore: update package.xml version to v0.6.0

---

src/test/record/records_service/test_frequency.py
src/test/record/records_service/test_period.py
src/test/record/records_service/test_range.py
src/test/record/test_column.py

Adding test for record directory.

test: add test for record

---

src/caret_analyze/architecture/architecture.py
src/caret_analyze/architecture/architecture_exporter.py
src/caret_analyze/architecture/architecture_loaded.py
src/caret_analyze/architecture/architecture_reader_factory.py
src/caret_analyze/architecture/combine_path.py
src/caret_analyze/architecture/graph_search.py
src/caret_analyze/architecture/reader_interface.py
src/caret_analyze/architecture/struct/callback.py
src/caret_analyze/architecture/struct/callback_group.py
src/caret_analyze/architecture/struct/communication.py
src/caret_analyze/architecture/struct/executor.py
src/caret_analyze/architecture/struct/message_context.py
src/caret_analyze/architecture/struct/node.py
src/caret_analyze/architecture/struct/node_path.py
src/caret_analyze/architecture/struct/path.py
src/caret_analyze/architecture/struct/publisher.py
src/caret_analyze/architecture/struct/service.py
src/caret_analyze/architecture/struct/subscription.py
src/caret_analyze/architecture/struct/timer.py
src/caret_analyze/architecture/struct/variable_passing.py
src/caret_analyze/architecture/util.py

Correction of architecture docstring
https://tier4.atlassian.net/browse/RT2-1856

fix(architecture): overhaul of docstrings

---

src/caret_analyze/infra/lttng/id_remapper.py
src/caret_analyze/infra/lttng/lttng.py
src/caret_analyze/infra/lttng/lttng_event_filter.py
src/caret_analyze/infra/lttng/ros2_tracing/data_model.py
src/caret_analyze/infra/lttng/ros2_tracing/processor.py
src/caret_analyze/value_objects/executor.py

chore: porting from forked repository

---

src/caret_analyze/infra/interface.py
src/caret_analyze/infra/lttng/architecture_reader_lttng.py
src/caret_analyze/infra/lttng/bridge.py
src/caret_analyze/infra/lttng/event_counter.py
src/caret_analyze/infra/lttng/lttng.py
src/caret_analyze/infra/lttng/lttng_event_filter.py
src/caret_analyze/infra/lttng/lttng_info.py
src/caret_analyze/infra/lttng/records_provider_lttng.py
src/caret_analyze/infra/lttng/records_source.py
src/caret_analyze/infra/lttng/ros2_tracing/data_model_service.py
src/caret_analyze/infra/lttng/ros2_tracing/processor.py
src/caret_analyze/infra/trace_point_data.py
src/caret_analyze/infra/yaml/architecture_reader_yaml.py

Correction of infra docstring
https://tier4.atlassian.net/browse/RT2-1856

fix(infra): overhaul of docstrings

---

src/caret_analyze/infra/lttng/lttng_info.py

When I run check_ctf on trace data measured with the "--record-clock" option enabled, I get a warning that the callback for /clock_recorder is missing.
```
$ ros2 caret check_ctf ~/caret_ws/nb/session-20250512164617
Succeed to find record_cpp_impl. the C++ version will be used.
8589251 events found.
loading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10189/10189 [00:00<00:00, 27624.48it/s]
loading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8579062/8579062 [01:35<00:00, 89657.72it/s]
filtered to 8589251 events.
WARNING : 2025-05-22 18:39:07 | This trace data has trace point from a package built without caret-rclcpp. …
```

fix: failed to find callback
