tier4/caret_analyze

caret_analyze/infra/interface.py, caret_analyze/infra/lttng/records_provider_lttng.py, caret_analyze/runtime/communication.py, caret_analyze/runtime/path.py, test/runtime/test_path.py, test/temp/value_objects/test_subscription_value_object.py
@hsgwa 
caret/rclcppで提供されているトレースポイントが入っているかを確認する機能
確認方法は以下
- プロセス内通信の場合
- Pub側：`ros2:rclcpp_intra_publish`があるか確認
- Sub側：`ros2:dispatch_intra_process_subscription_callback`があるか確認
- プロセス間通信の場合
- Pub側：ros/rclcppのトレースポイントで足りるため確認不要
- Sub側：`ros2:dispatch_subscription_callback`があるか確認
本機能はwarningを出すだけに留まる
ndt_scan_matcherのみros/rclcppでビルドした時のトレースデータ
https://drive.google.com/drive/folders/15QqkOsSvFwj8wGkyUwHNxijxqaeA1-CK
=> verify_trace_points

package.xml
Added tqdm to package.xml because it is used in [progress.py](https://github.com/tier4/CARET_analyze/blob/0579d8755f26d4fcd4f8a8e2f9e904f5b582e3ad/caret_analyze/common/progress.py) and [lttng.py](https://github.com/tier4/CARET_analyze/blob/0579d8755f26d4fcd4f8a8e2f9e904f5b582e3ad/caret_analyze/infra/lttng/lttng.py).
=> fix: Add dependency to tqdm

caret_analyze/infra/lttng/records_provider_lttng.py
When fixing a bug when both intra-process and inter-process communication was used, the latency calculation method was implemented incorrectly.
https://github.com/tier4/CARET_analyze/commit/24a2883296b058c2a87848449e1d9329ee0301e2
=> fix: negative comm latency

src/test/test_mypy.py
This PR disables mypy tests in github actions since mypy test is to be officially supported in v0.4 or later.
=> chore: skip mypy tests in github actions

docs/.pages, docs/architecture.md, docs/common.md, docs/index.md, docs/infra.md, docs/record.md, docs/value_objects.md, mkdocs.yaml, src/caret_analyze/runtime/__init__.py
@hsgwa @takam5f2 
[CARET_analyzeのAPIリストをユーザ向けと開発者向けでセクション分けする](https://tier4.atlassian.net/browse/T4PB-18089) が完了したので、ご確認をお願いいたします。
修正内容は以下です。
- plot, runtime, exceptions 以外のモジュールのページを API for developer セクションに追加
- mkdocs.yaml にあるページレイアウトを .pages に移動する
- mkdocstring プラグインの show_submodule オプションを False に変更 （重複が発生するため）
- PaseBase クラスを runtime モジュールの `_all_` に追加
=> docs: add pages of API for developer and fix document generation methods

src/caret_analyze/value_objects/message_context.py, src/test/value_objects/test_message_context.py
@hsgwa 
[Path.verify() 関数の実装見直し・修正](https://tier4.atlassian.net/browse/T4PB-17110) の作業が完了したので、ご確認をお願いいたします。
既存の path.verify 関数で、以下２つの検知はできていたため、原因を細分化して警告メッセージを出すように変更しました。
- ノードのコールバックと Publish するトピックの紐づけが出来ていない
- Variable_passings が指定されてない
以下は、「[message_context に 'callback_chain' を使用 ∧ コールバックとpublisher の紐づけができていないアーキテクチャファイル](https://drive.google.com/file/d/1OkSAc9prn3IfnCxV1K2XCKE0jsXZELeu/view?usp=sharing)」に対する警告文です。
> WARNING : 2022-06-28 11:04:15 | callback-chain is empty. The callback is not associated with the publisher. publisher topic name: /topic4
=> feat: clarify the reason for the warning in CallbackChain.verify

src/caret_analyze/infra/lttng/lttng.py
@hsgwa
Lttng.get_trace_range の戻り地の型を int 型から datetime 型に修正しました。
また、一点既存の typo を修正しました。
=> fix: fix 'int' to 'datetime' in Lttng.get_trace_range

src/caret_analyze/common/util.py
find_similar_one関数
find_similar_one_multi_keys関数
のdocstring追加用PR
=> fix: add docstring to find similar one function

src/caret_analyze/record/record_cpp_impl.py, src/test/record/test_record.py
This PR fix the following error
```
from caret_analyze.record.record_cpp_impl import RecordCppImpl, RecordsCppImpl
records =RecordsCppImpl(None, ['column'])
record = RecordCppImpl()
records.append(record)
```
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 records.append(record)
File ~/ros2_caret_ws/build/caret_analyze/caret_analyze/record/record_cpp_impl.py:58, in RecordsCppImpl.append(self, other)
56     msg = 'Contains an unknown columns. '
57     msg += f'{unknown_columns}'
---> 58     raise InvalidArgumentError(msg)
60 self._records.append(other)
InvalidArgumentError: Contains an unknown …
```
=> fix(records_cpp): invalid argument error

src/test/record/test_record.py
This PR changes test scope.
In github action, records_cpp-related tests are skipped.
In local, test raises ModuleNotFoundError.
=> test(records_cpp): enable ModuleNotFoundError in local environment

src/caret_analyze/record/interface.py, src/caret_analyze/record/record.py, src/caret_analyze/record/record_cpp_impl.py, src/package.xml, src/test/record/test_record.py
This PR enables multi argument dispaching such as:
```
records = Records()
records.append(Record({'key': 1})) # conventional
records.append({'key': 1}) # new
```
This patch includes additional third-party package [multimethod].
rosdep installation supports multimethod installation though, users may need to run "rosdep update".
=> refactor(records): support multiple argument dispatching to append

src/caret_analyze/plot/__init__.py, src/caret_analyze/plot/bokeh/callback_info.py, src/caret_analyze/plot/bokeh/callback_info_factory.py
[CARET_analyze で jitter としてしまった箇所を period に統一する](https://tier4.atlassian.net/browse/T4PB-19289) の作業が完了したので、ご確認をお願いいたします。
作業としては、機械的に jitter を period にリネームしただけです。
テストコードを添付させていただきます。
- [Yano環境の出力結果](https://drive.google.com/file/d/1CpPPN9zb2llZGi9aE4omely4Wp4-MAVS/view?usp=sharing)
- [テストコード(ipynb)](https://drive.google.com/file/d/1SrlN7QVh6dICg4v0IQ9wBYGMUXPw8stx/view?usp=sharing)
- [使用したアーキテクチャファイル](https://drive.google.com/file/d/1dRInIE2HquYziQ-qLakVL3_nAyrUMeh5/view?usp=sharing)
- [使用したトレースデータ](https://drive.google.com/file/d/1hALgv-iwjy54nJ_M_W3f0Kgkvc0OlEEx/view?usp=sharing)
=> chore: rename 'jitter' to 'period' in Plot

src/caret_analyze/record/response_time.py
- It takes very long time to create a `ResponseTime` object with the current implementation
- Related link (TIER IV internal) : https://tier4.atlassian.net/browse/T4PB-20037
- Call `records.data` at the outside of loop
- Result for sample trace data (15 min Autoware trace)
- before this change: 70 minutes
- after this change: 1 second
=> perf(response_time): improve ResponseMap creation time

src/caret_analyze/infra/lttng/lttng_info.py, src/test/infra/lttng/test_lttng_info.py
This patch fixes:
```
Architecture('lttng', 'path/to/ctf')
---
ValueError: You are trying to merge on object and float64 columns.
If you wish to proceed you should use pd.concat
```
=> fix(lttng_info): trying to merge on object and float64 columns

src/caret_analyze/infra/lttng/lttng.py, src/caret_analyze/infra/lttng/ros2_tracing/data_model.py, src/caret_analyze/infra/lttng/ros2_tracing/processor.py, src/test/infra/lttng/test_architecture_reader_lttng.py, src/test/infra/lttng/test_lttng.py
This PR improves processing time and memory usage for Lttng class.
For now, I removed ros2_tracing classes.
memory usage was improved, but processing time was worse than with cache.
[Without event filter]
Before (without cache)
15.8s, 333MB
Before (with cache)
6.3s, 335MB
After
18.5s, 102MB
[With event filter]
Before (without cache)
13.2s, 274MB
Before(with cache)
3.84s, 245MB
After
13.9 s, 23MB
=> perf(lttng): improve memory consumption

src/caret_analyze/infra/lttng/lttng.py, src/test/infra/lttng/test_latency_definitions.py, src/test/infra/lttng/test_lttng.py
**Note: This patch should be applied after #117** 
In some cases, an error occurred when loading the cache and LttngEventFilter.
To reproduce, used data are located here : 
https://drive.google.com/drive/folders/1Zw-V8jvlC22EJC87gEqSsQJqjU5KFYoA?usp=sharing
This patch fixes:
```
461386 events found.
loading:   0%|                                                                                        | 2/461386 [00:00<00:30, 15114.61it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 lttng = Lttng(tracing_log_path, event_filters=[LttngEventFilter.duration_filter(5, 10)])
3 arch = Architecture('yaml', architecture_path)
4 app = Application(arch, …
```
=> fix(lttng): unsupported operand type error with cache.

src/caret_analyze/plot/bokeh/message_flow.py
This fixes a bug; in granularity=node of message_flow, publish was unintentionally erased in column name.
=> fix(plot): missing column name with node granularity

src/caret_analyze/infra/lttng/event_counter.py
caret-rclcpp assertion is checked by whether caret-rclcpp tracepoits are recorded.
However, when all nodes publish with iter-process communication, no caret-rclcpp tracepoints are recorded.
- message_construct
- rclcpp_intra_publish
- dispatch_subwscription_callback
- dispatch_intra_subscription_callback
If target application doesn't have any subscription and intra-process publish, the original implementation incorrectly raises an error.
This PR modifies caret-rclcpp check from assertion to warning.
To reproduce: https://drive.google.com/drive/folders/1og8VNwxQdb8Bo-zoSO6_E2IPiTDWx0TE?usp=sharing
```
from caret_analyze import Lttng
Lttng(''aaa_sample')
InvalidTraceFormatError                   Traceback (most recent call last)
Input In [2], in …
```
=> fix(lttng): change caret-rclcpp violation as warn

src/caret_analyze/plot/bokeh/communication_info_interface.py, src/caret_analyze/plot/bokeh/pub_sub_info_interface.py
@hsgwa 
This PR change plot APIs to return figure object.
In addition, for use cases where the graph is formatted after output, I have added an `interactive` option to the show() method of the PubSubTimeSeriesPlot class.
If `interactive=True` or `export_path` are specified, the figure object is not returned.
To reproduce: https://drive.google.com/drive/folders/12tPl0kwBzHaC5amOa1od5Qwmve6yZ_nI?usp=sharing
=> chore(plot): change plot APIs to return figure object

src/caret_analyze/plot/bokeh/pub_sub_info_interface.py, src/test/plot/bokeh/test_pub_sub_info_interface.py
This PR fixes an IndexError that occurred in the get_node_name() and get_callback_name() functions in pub_sub_plot_interface.py.
=> fix(plot): add handling of cases where there is no node/callback name

src/caret_analyze/plot/bokeh/util.py
In bokeh, fixing the tick width will cause a SIGILL error when scaling down.
In the current implementation, this same thing happens when visualizing.
This is because there are cases where the minimum value for to_dataframe() contains columns with zeros.
This patch fixes the SIGILL error during visualization.
BUG: SIGILL error raises.
EXPECT: no error.
=> fix(plot): sigill error during bokeh plotting

src/caret_analyze/record/record.py
This PR fixes the following error during pandas.Dataframe().
```
E           ValueError: columns cannot be a set
```
The reason for the error is that the version of pandas on PyPI has been increased to 1.5.0.
=> fix(record): pandas.Dataframe error 'columns cannot be a set error'

src/caret_analyze/value_objects/callback.py, src/caret_analyze/value_objects/publisher.py, src/caret_analyze/value_objects/subscription.py, src/caret_analyze/value_objects/timer.py
This PR adds node name to summary info.
Summary class is UserDict class and it helps developers to understand the primary information of the instance.
node name is necessary for these classes to identify.
=> chore(value_objects): add node name to summary dict

src/caret_analyze/infra/lttng/lttng.py
This PR fixes a bug where duration_filter results differed depending on whether the cache exists.
See attached figure for the cause of the bug.
=> fix(lttng): bug with different range of duration_filter when there is no cache

src/caret_analyze/plot/bokeh/message_flow.py, src/caret_analyze/runtime/path.py
This PR renames from `Path.callbacks` to `Path.callback_chain`
The current `Path.callbacks` property returns the callbacks that comprise the path when `callback_chain` is specified in the definition of the path.
The reason for this PR is that `callback_chain` is rarely specified in the definition of a path, and I plan to add a new property that will return all callbacks for the nodes that composes the path.
=> chore(runtime): rename from Path.callbacks to Path.callback_chain

src/caret_analyze/exceptions.py, src/caret_analyze/infra/lttng/ros2_tracing/data_model_service.py, src/test/infra/lttng/ros2_tracing/test_data_model_service.py
This PR adds the  API to get the node name from callback group address based on Ros2DataModel.
Related thread: https://emb4hq.slack.com/archives/C03TE75R9C0/p1661140765913979?thread_ts=1661127490.661349&cid=C03TE75R9C0
=> feat(ros2_tracing): add API to get node name from callback group address based on Ros2DataModel.

src/caret_analyze/runtime/path.py
This PR adds the `Path.callbacks` property that returns callbacks in all nodes that comprise the node path.
The implementation is the same as follows: https://github.com/tier4/CARET_analyze/blob/2202e1b133fe89a5fe56b9081ff9482128d8a4f2/src/caret_analyze/plot/bokeh/callback_info_interface.py#L50.
=> feat(runtime): add callbacks property in Plot object

src/caret_analyze/infra/lttng/lttng_info.py
This PR adds the target node name to the following warning message.
`Multiple executors using the same callback group were detected`
To reproduce: https://drive.google.com/drive/folders/1AomDMGYDyyg2wdUgaLijN9Nq_smIbvCV?usp=sharing
=> feat(lttng): add node name to warning message

src/caret_analyze/record/__init__.py, src/caret_analyze/record/latency.py, src/test/record/test_latency_records.py
This PR add API to get latency time-series data in record package.
The implementation is a modification of the following parts of the plot package.
https://github.com/tier4/CARET_analyze/blob/3a1ed200e8206fe4ef7eea184325e314b597c493/src/caret_analyze/plot/bokeh/callback_info.py#L68
To reproduce: https://drive.google.com/drive/folders/1xabhXzw6DmuRrVSc-VWKRH_TrPVETjeR?usp=sharing
=> feat(record): add API to get latency time-series data

src/caret_analyze/architecture/architecture_loaded.py, src/caret_analyze/architecture/reader_interface.py, src/caret_analyze/infra/lttng/architecture_reader_lttng.py, src/caret_analyze/infra/lttng/lttng.py, src/caret_analyze/infra/lttng/lttng_info.py, src/caret_analyze/infra/lttng/value_objects/__init__.py, src/caret_analyze/infra/lttng/value_objects/callback_group.py, src/caret_analyze/infra/yaml/architecture_reader_yaml.py
This PR adds the target node name to the following warning message.
`Failed to find callback group`
To reproduce: https://drive.google.com/drive/folders/1AomDMGYDyyg2wdUgaLijN9Nq_smIbvCV?usp=sharing
=> feat: add node names in warning message when callback group not found

src/caret_analyze/record/__init__.py, src/caret_analyze/record/period.py, src/test/record/test_period.py
This PR add API to get period time-series data in record package.
The implementation is a modification of the following parts of the plot package.
https://github.com/tier4/CARET_analyze/blob/3a1ed200e8206fe4ef7eea184325e314b597c493/src/caret_analyze/plot/bokeh/callback_info.py#L122
To reproduce: https://drive.google.com/drive/folders/1BV7G34uA7cLB6XoN9xj7NAjOboh-rxmC?usp=sharing
=> feat(record): add API to get period time-series data

src/caret_analyze/record/record.py
This PR fixes following error as workaround
```
Lttng('/path/to/ctf')
---
TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'
The above exception was the direct cause of the following exception:
TypeError                                 Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 lttng = Lttng('autoware_without_tilde')
File ~/ros2_caret_ws/build/caret_analyze/caret_analyze/infra/lttng/lttng.py:231, in Lttng.__init__(self, trace_dir_or_events, force_conversion, event_filters, store_events, validate)
229 self._info = LttngInfo(data)
230 self._source: RecordsSource = RecordsSource(data, self._info)
--> 231 self._counter = EventCounter(data, …
```
=> fix: to_dataframe type error "cannot cast from dtype('float64') to dtype('int64')"

src/test/infra/lttng/test_lttng_info.py
This PR fixes errors caused by : https://github.com/tier4/CARET_analyze/pull/163
=> fix(lttng): dtype miss-match error

src/caret_analyze/plot/bokeh/histogram.py, src/caret_analyze/plot/bokeh/histogram_interface.py, src/caret_analyze/plot/bokeh/plot_factory.py
Signed-off-by: bopeng-saitama <peng.b.203@ms.saitama-u.ac.jp>
Add histogram API.
Use method.
```
arch = Architecture('yaml', arch_file)
lttng = Lttng(trace_data)
app = Application(arch, lttng)
path = app.get_path(target_path)
path1 =  app.get_path('target_path')
path2 =  app.get_path('Sensing')
plot = Plot.create_response_time_histogram_plot(path1,path2)
plot.show()
```
=> feat: add api showing histogram of response time

src/caret_analyze/infra/lttng/lttng.py, src/test/infra/lttng/test_lttng.py
Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>found
=> feat(lttng): add FileNotFound exception when file is not found

src/requirements.txt
CARET doesn't run on Bokeh 3.x at the moment.
=> chore: fix bokeh version 2.x

src/caret_analyze/architecture/struct/callback.py
Need to maintain existing code for future implementation of service-related callback classes
=> refactor(callback): specify the name of the keyword argument

src/caret_analyze/architecture/architecture.py, src/caret_analyze/runtime/application.py
This PR adds `publishers` and `subscriptions` properties.
- app.publishers / app.subscriptions
- arch.publishers / arch.subscriptions
After this PR is merged, #180 can be merged.
=> chore: add publishers and subscriptions properties

src/caret_analyze/architecture/architecture_loaded.py, src/caret_analyze/architecture/reader_interface.py, src/caret_analyze/infra/lttng/architecture_reader_lttng.py, src/caret_analyze/infra/lttng/lttng.py, src/caret_analyze/infra/lttng/lttng_info.py, src/caret_analyze/infra/lttng/ros2_tracing/data_model_service.py, src/caret_analyze/infra/yaml/architecture_reader_yaml.py, src/test/infra/lttng/ros2_tracing/test_data_model_service.py
This PR add callback symbol name to warning message in Lttng and Architecture.
This PR contains modifications to API in DataModelService.
To reproduce: https://drive.google.com/drive/folders/1dWd2o6rtVhe56VXRnEdPM9G4H6RvnN1c?usp=share_link
The current implementation does not support **the case where multiple node names or multiple callback symbols are associated with a handle** (such as `timer_handle`, `subscription_handle`, and `service_handle`).
This is because the data structure of the return value is complicated in the above case.
The above case did not occur with Autoware trace data, but please let me know if this implementation is undesirable.
```
assert len(match_nodes) == 1
~~~
assert len(match_callback_symbols) == 1
```
=> feat: add callback symbol name to warning message in Lttng and Architecture

src/caret_analyze/infra/lttng/lttng_info.py
The following warning appears when loading lttng trace log data.
```
/home/aaai/ros2_caret_ws/build/caret_analyze/caret_analyze/infra/lttng/lttng_info.py:439: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
for _, group_df in concat_df.groupby(['callback_group_addr']):
```
Environment:
- Ubuntu 22.04
- Python 3.10.6
- pandas 1.5.0
How to reproduce:
- Run `ros2 caret check-ctf` for the following trace log
- https://github.com/tier4/CARET_report/releases/download/20220831/autoware_launch_trace_20220826-105249_universe_rosbag.zip
=> fix: fix warnings for pandas.groupby

src/caret_analyze/architecture/architecture.py
Even though the annotation on the return value was `Tuple[CallbackStructValue]`, the actual return value was `Tuple[Tuple[CallbackStructValue]]`.
Fix this to use function `Util.flatten()`
Signed-off-by: rokamu623 <r.okamura.061@ms.saitama-u.ac.jp>
=> fix: callbacks return value

pytest.ini, src/caret_analyze/infra/lttng/lttng.py, src/test/infra/lttng/test_lttng.py
This PR adds the ability to automatically update the cache.
It solves the problem of the old cache being loaded after remeasurement.
It implements the following:
- If there is a cache, compare the measurement time of the cache with the measurement time of the ctf file.
- If the measurement times are different, the cache is generated again.
=> feat(lttng): automatic cache updating

src/caret_analyze/architecture/architecture.py, src/caret_analyze/runtime/application.py
This PR modify topic name property to support publisher-only / subscription-only case.
https://github.com/tier4/CARET_analyze/pull/179 is applied beforehand.
=> chore: support publisher-only / subscription-only topic names

src/caret_analyze/architecture/architecture.py
This PR ignores following flake8 errors which occours recently.
```
./src/caret_analyze/architecture/architecture.py:156:5: F811 redefinition of unused 'publishers' from line 146
def publishers(self) -> Tuple[PublisherStructValue, ...]:
^
./src/caret_analyze/architecture/architecture.py:161:5: F811 redefinition of unused 'subscriptions' from line 151
def subscriptions(self) -> Tuple[SubscriptionStructValue, ...]:
^
2     F811 redefinition of unused 'publishers' from line 146
```
=> chore: ignore weird flake8 errors

src/caret_analyze/infra/lttng/lttng_info.py, src/caret_analyze/infra/trace_point_data.py
Applying https://github.com/tier4/CARET_analyze/pull/193 with multimethod-1.8, a recursion error occurs.
This patch fixes the issue.
To reproduce:
```
pip install -U 'multimethod<1.9' # latest version is 1.9
python -c 'import caret_analyze'
```
```
RecursionError: maximum recursion depth exceeded in __subclasscheck__
```
=> fix(infra): disable multimethod in add_column function to avoid exceeding recursive depth

src/caret_analyze/common/__init__.py, src/caret_analyze/common/type_check_decorator.py, src/caret_analyze/plot/bokeh/callback_sched.py, src/caret_analyze/plot/bokeh/histogram.py, src/caret_analyze/plot/bokeh/histogram_interface.py, src/caret_analyze/plot/bokeh/message_flow.py, src/caret_analyze/plot/bokeh/plot_factory.py, src/caret_analyze/plot/graphviz/chain_latency.py, src/package.xml, src/test/common/test_type_check_decorator.py
This PR adds a dynamic type check decorator and applies it to APIs that accept `Path` as input.
The dynamic type checking use [pydintic](https://pydantic-docs.helpmanual.io/usage/validation_decorator/). (See [this page](https://tier4.atlassian.net/browse/T4PB-20204?focusedCommentId=104443) for comparison of pydintic with other libraries.)
If pydantic cannot import, the process is performed without type checking.
- JIRA ticket: https://tier4.atlassian.net/browse/T4PB-20204
- To reproduce: https://drive.google.com/drive/folders/1PeBu4seVX4Z7Md6EHD4-ce3TiioPlGIh?usp=share_link
=> feat: add dynamic type check decorator & use it to check Path input

src/caret_analyze/infra/lttng/records_provider_lttng.py, src/test/infra/lttng/test_latency_definitions.py
If there are drops, the data for the communication.to_records would be as follows:
| publish | callback_start|
|-------------|--------------------|
|0 | 1
| 4 | 5|
|2 | None|
This PR adds sort by timestamp of rclcpp_publish
| publish | callback_start|
|-------------|--------------------|
|0 | 1
|2 | None|
| 4 | 5|
=> fix(intra): add sorting to communication.to_records and publisher.to_records

src/caret_analyze/plot/plot_facade.py
This PR removes deprecated `Plot.create_callback_jitter_plot()` method.
=> chore(plot): remove deprecated jitter plot

src/caret_analyze/record/record.py, src/caret_analyze/record/record_cpp_impl.py, src/test/record/test_record.py
This PR adds InvalidArgumentError for following case.
```python
left_records.merge_sequential(
**args,
columns=['not_exist_column_name'],
how='left'
)
```
These validation are applied for `merge` and `merge_sequential_for_addr_track` as well.
=> fix: validation for unknown columns

src/caret_analyze/architecture/struct/node.py
- Due to `list` annotation, `'type' object is not subscriptable` error occurs when running cli commands like `ros2 caret check_ctf` in Galactic
- Only one part uses `list` while all the other parts use `List` for annotation
- This PR changes `list` annotation to `List` annotation
None
None
=> fix(architecture): annotation for list to avoid runtime error

src/caret_analyze/infra/lttng/records_provider_lttng.py
The format of callback in record is `{callback_name}/timestamp` , and our new stacked bar graph expects that it ends with `{node_name}/callback_o/ooo`
If the name is like `{node_name}/ooo` , we cannot recognize whether it is callback or topic in stacked bar graph at glance.
When `callback_name` is not found in column in record, `callback_x` is added to keep the same style.
(`x` in `callback_x` will be appropriate because we don't know which callback runs)
https://github.com/tier4/CARET_analyze/pull/263
I'm sorry but I'm the one who said the current callback name is okay. However, I found it doesn't work well with stacked bar graph.
After all checkboxes …
=> fix: callback name style of the first callback

src/caret_analyze/record/records_service/stacked_bar.py, src/test/plot/stacked_bar/test_latency_stacked_bar.py, src/test/record/records_service/test_stacked_bar.py
Include the last callback_end to stacked bar graph
```py
target_path = app.get_path(target_path.path_name)
target_path.include_first_callback = True
target_path.include_last_callback = True
message_flow(target_path)
Plot.create_response_time_stacked_bar_plot(target_path, case='best').show(full_legends=True)
Plot.create_response_time_stacked_bar_plot(target_path, case='worst').show(full_legends=True)
```
https://tier4.atlassian.net/browse/T4PB-26673
- I fix this issue by myself because I need this urgently
- The first callback is added without any modification. Could you check if it's as expected from the view point of code?
After all checkboxes are …
=> fix: include last callback to stacked bar graph

src/caret_analyze/plot/visualize_lib/bokeh/message_flow_source.py
The first and last callback times added to `message_flow` at https://github.com/tier4/CARET_analyze/pull/263. A bug was found where the last callback was not included when the `message_flow` was used with option `granularity='node'`. This problem was caused by the way the column name was formatted when `granularity='node'`.
- https://github.com/tier4/CARET_analyze/pull/263
=> fix(message_flow): include last callback to message flow with granularity='node'

src/caret_analyze/plot/message_flow/message_flow_plot.py
This PR enable ywheel zoom for message flow by default.
This bug was raised in a comment [here](https://github.com/tier4/CARET_analyze/pull/267#issuecomment-1491633869).
- Refactoring PR: https://github.com/tier4/CARET_analyze/pull/267
- To reproduce:
- [ipynb, html](https://drive.google.com/drive/folders/1xkZ897Ieqd1M2kenmA6vD8evCGHZ_quv?usp=share_link)
- [architecture file](https://drive.google.com/file/d/1W9PDyj046xzapMA-p3o6HWtUhMA8JhIG/view?usp=share_link)
- [trace data](https://drive.google.com/file/d/1xy1L4c-eGi9RSHog1qNgovTcwxoM74Z9/view?usp=share_link)
=> fix(plot): enable ywheel zoom for message flow by default

src/caret_analyze/plot/callback_scheduling/callback_scheduling_plot.py, src/caret_analyze/plot/message_flow_old.py, src/caret_analyze/plot/plot_base.py
This PR removes `export_path` argument and set return value to None in show() method.
The `export_path` argument is not required because of the existence of the save() method.
- JIRA ticket: https://tier4.atlassian.net/browse/RT2-627
- Discussion: https://tier4.atlassian.net/browse/RT2-445?focusedCommentId=119691
- To reproduce:
- [ipynb](https://drive.google.com/drive/folders/1WgkHpz2Ic0UT3_uF0rfcVYP7LZKov-Mc?usp=share_link)
- [architecture file](https://drive.google.com/file/d/1W9PDyj046xzapMA-p3o6HWtUhMA8JhIG/view?usp=share_link)
- [trace data](https://drive.google.com/file/d/1xy1L4c-eGi9RSHog1qNgovTcwxoM74Z9/view?usp=share_link)
I have confirmed that there are no regressions using CARET_report.
The PR author …
=> refactor(plot): refactor Plot.show() method

src/caret_analyze/architecture/architecture_loaded.py, src/caret_analyze/infra/lttng/records_source.py
Minor fixes to problems with warnings when generating Lttng, Architecure objects.
The fixes addressed the following issues.
- Fixes to sequential numbering of service callback groups.
- `Duplicated callback group name.` warnings are suppressed.
- Fixes to destructive methods in `infra.lttng.records_source.py`.
- Modified to process cloned data instead of directly referencing data.
=> fix: minor changes for records processing

src/caret_analyze/infra/lttng/records_source.py
In https://github.com/tier4/CARET_analyze/pull/263, I added `tid` (thread id) information to the `rclcpp_callback_start` event to evaluate the time from the start node callback to publish. This caused a discrepancy in the list of column names between Records and Record.
example:
```
lttng = Lttng(rosbag_path)
arch = Architecture('lttng', rosbag_path)
app = Application(arch, lttng)
cb = app.callbacks[0]
records = cb.to_records()
print(records.columns)
>>> ['/actuator_dummy_node/callback_0/callback_start_timestamp',
'/actuator_dummy_node/callback_0/callback_end_timestamp']
print(records.data[0].columns)
>>>> {'/actuator_dummy_node/callback_0/callback_end_timestamp',
'/actuator_dummy_node/callback_0/callback_start_timestamp',
'tid'}
```
remove `tid` from record columns.
- …
=> fix: remove tid from callback record

src/caret_analyze/plot/visualize_lib/bokeh/stacked_bar.py, src/caret_analyze/plot/visualize_lib/bokeh/util/hover.py
This PR adds label names and latency to the stacked bar legend.
- JIRA ticket: https://tier4.atlassian.net/browse/RT2-324
- To reproduce: https://drive.google.com/drive/folders/1chovgqh3_PRK-pk-BXgQhfs0mIWw6Qbp?usp=share_link
I have confirmed that there are no regressions using CARET_report.
=> fix(plot): fix legend for stacked bar plot

src/caret_analyze/plot/graphviz/chain_latency.py
This PR fixes to draw callback latencies at the first and last for `chain_latency`.
- Ticket: https://tier4.atlassian.net/browse/RT2-700
- Discussion: https://emb4hq.slack.com/archives/C05311Y9L2X/p1683795835886779
- To reproduce: https://drive.google.com/drive/folders/12UGwclt5yaY9UfuP38OFvcN7GyrvWjbN?usp=share_link
=> feat(plot): draw callback latency at fitst and last in chain_latency

src/caret_analyze/infra/lttng/event_counter.py, src/test/infra/lttng/test_event_counter.py
After #PR296, the warning given by `ros2 caret check_ctf` was not appropriate.
CARET uses the original tracepoint definition to calculate latency.
`ros2 caret check_ctf` is a checking command for the above tracepoints.
If there were no original tracepoints, we output the warning, but the following warning was also output even when the analysis could be carried out normally.
```
Failed to find trace point added by caret-rclcpp.
To check whether binary are built with caret-rclcpp,
run CARET CLI : ros2 caret check_caret_rclcpp.
```
The warnings are erroneously output in the following cases：
In the following cases, analysis could be performed but a warning was output.
- Built with `caret-rclcpp`, but the application doesn't have intra-process communication
- …
=> fix: check_ctf warning message

src/caret_analyze/common/type_check_decorator.py, src/test/common/test_type_check_decorator.py
In pydantic 2.1.1, pytest related to @type_check_decorator is causing an error.
This PR fixes the errors noted by mypy and unit tests (test_type_check_decorator.py).
The pydantic identification names of the types refer to the following: https://docs.pydantic.dev/latest/errors/validation_errors/
reference: https://github.com/tier4/CARET_analyze/pull/302
reference: https://github.com/tier4/CARET_analyze/pull/311
=> fix: mypy warning in type_check_decorator by signiture

src/caret_analyze/record/records_service/response_time.py, src/test/record/records_service/test_latency_records _all.py, src/test/record/records_service/test_response_time_all.py
As a method for calculate `ResponseTime`, in addition to the existing worst/best, a method is implemented to calculate the `ResponseTime` from all inputs (even if the outputs are the same).
The following APIs have been added:
- `ResponseTime.to_all_records()`
- return Records including response times for all case.
- `ResponseMapAll` class
- generate Records which is returned by `ResponseTime.to_all_records()`.
Jira: https://tier4.atlassian.net/browse/RT2-825
regression test of CARET_report
=> feat: response time all

src/caret_analyze/plot/stacked_bar/latency_stacked_bar.py, src/caret_analyze/record/records_service/response_time.py, src/test/record/records_service/test_response_time.py
Implement `to_best_case_records()` and `to_worst_case_records()` in the `ResponseTime class`, which are APIs in the same format as `to_records()` in `Latency` class.
Jira: https://tier4.atlassian.net/browse/RT2-886
=> refactor: response time class api

src/caret_analyze/record/records_service/response_time.py, src/test/record/records_service/test_response_time.py
=> feat: response time worst in input

src/requirements.txt
- Pandas v2.1.0 was released on 2023/08/30, but CARET_analysis fails with this version.
- It looks v2.1.0 has a bug: https://github.com/pandas-dev/pandas/issues/54848
- As a workaround, CARET should avoid using v2.1.0
```
takeshiiwanari@dpc2205002:~/work/tracedata/xx1/20230616$ ros2 caret check_ctf -d session-20230616162550_odaiba
/usr/local/lib/python3.10/dist-packages/pandas/core/arrays/masked.py:62: UserWarning: Pandas requires version '1.3.4' or newer of 'bottleneck' (version '1.3.2' currently installed).
from pandas.core import (
Succeed to find record_cpp_impl. the C++ version will be used.
36347468 events found.
loading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36347468/36347468 [11:10<00:00, …
```
=> fix: pandas version to avoid 2.1.0

src/caret_analyze/record/record.py, src/requirements.txt
Temporary handling of mypy warnings.
- Add # type: ignore for record.py
- For safety reasons, it should be removed later.
- Update mypy to v0.981
- It should be update v1.5.2 later.
Jira: https://tier4.atlassian.net/browse/RT2-944
=> fix: temporary handling of mypy warnings

src/requirements.txt
- As of 2023/09/08, `setuptools==68.2.0` is installed and it causes the following CARET build error.
- This PR avoid installing the latest version of setuptools as a workaround
```sh
--- stderr: tracetools_trace                                                                                                                                                
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
rc = await self.task(*args, **kwargs)
File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
return await task_method(*args, **kwargs)
File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 51, in build
setup_py_data = get_setup_data(self.context.pkg, …
```
=> fix(workaround): avoid the latest setuptools which causes build error

src/caret_analyze/plot/histogram/__init__.py, src/caret_analyze/plot/histogram/histogram_plot.py, src/caret_analyze/plot/histogram/histogram_plot_factory.py, src/caret_analyze/plot/plot_facade.py, src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py, src/caret_analyze/plot/visualize_lib/visualize_lib_interface.py, src/caret_analyze/runtime/path.py
Complete the API to display the response time of a path in a histogram.
In addition, an API to display the latency of Node and Communication in a histogram will be implemented.
Jira: https://tier4.atlassian.net/browse/RT2-886
=> feat: add histogram api

.github/workflows/pytest.yaml
This PR modifies `pytest` GitHub Actions workflow to save package list. It helps developers to find causes in case an error happens and it's caused by package version upgraded. The results of `dpkg -l` and `pip3 list` are saved.
Package list can be found in Actions -> pytest -> Artifacts -> package_list
None
None
=> ci: upload package list

src/caret_analyze/plot/histogram/histogram_plot_factory.py, src/caret_analyze/plot/plot_facade.py, src/caret_analyze/plot/stacked_bar/latency_stacked_bar.py, src/caret_analyze/plot/stacked_bar/stacked_bar_plot.py, src/caret_analyze/plot/stacked_bar/stacked_bar_plot_factory.py, src/caret_analyze/plot/timeseries/response_time_timeseries.py, src/caret_analyze/plot/timeseries/timeseries_plot_factory.py, src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py, src/caret_analyze/record/records_service/response_time.py, src/test/record/records_service/test_response_time.py, src/test/record/records_service/test_response_time_all.py
The current option names for ResponseTime diverge from the intuitive image.
The option names have been changed as follows:
- worst -> worst-with-external-latency
- worst-in-input -> worst
Jira: https://tier4.atlassian.net/browse/RT2-888
=> fix:  rename option of ResponseTime

src/requirements.txt
CARET build was failed with `setuptools` 68.0.0. But it was fixed with latest version of `setuptools` 68.2.2.
This PR will remove the temporary fix and use the latest version of `setuptools`.
https://setuptools.pypa.io/en/stable/history.html
=> fix: remove temporary fix for version restriction of setuptools

src/requirements.txt
CARET_analyze causes installation errors with setuptools 68.0.0, this PR specified the latest version (68.2.2) or higher, just in case.
build results:
```
Finished <<< caret_trace [18.0s]
Summary: 23 packages finished [51.7s]
13 packages had stderr output: caret_analyze caret_analyze_cpp_impl caret_trace cyclonedds rclcpp ros2caret ros2trace test_tracetools_launch tracetools tracetools_launch tracetools_read tracetools_test tracetools_trace
```
=> fix: specify setuptools version >= 68.2.2

src/requirements.txt
In [this PR](https://github.com/tier4/CARET_analyze/pull/324), pandas==2.1.0 is ignored and an older version is installed as a workaround. Since newer version of pandas is released, the workaround should be removed.
https://tier4.atlassian.net/browse/RT2-942
I confirmed the error which occurred with pandas==2.1.0 is fixed
=> chore: upgrade pandas version

.github/workflows/pytest.yaml, src/test/record/test_record.py
In the "Records" class (used in GitHub Actions) and the "RecordsCppImpl" class (used in the local execution environment), it has been observed that they exhibit different behaviors for the same input. To address this issue, "RecordsCppImpl" will be built and used in GitHub Actions. Additionally, when there are no changes in "RecordsCppImpl," caching will be employed to optimize the build process for increased speed.
https://tier4.atlassian.net/browse/RT2-590
=> fix:  using caret_record_cpp_impl on GitHub Actions

src/caret_analyze/record/records_service/response_time.py, src/test/infra/lttng/test_latency_definitions.py, src/test/record/records_service/test_response_time.py, src/test/record/records_service/test_response_time_all.py
The method of calculating ResponseTime for the `best` and `worst-with-external-latency` cases has been changed to be the same as for `all` and `worst` case.
Jira: https://tier4.atlassian.net/browse/RT2-889
=> feat: refactor best/worst record api in response time

src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
- Current implementation for histogram graph uses `Probability` for Y-axis. However, `Probability` (`density=True`) calculated by numpy.histogram is a little confusing. According to [the reference](https://numpy.org/doc/stable/reference/generated/numpy.histogram.html), ` the sum of the histogram values will not be equal to 1 unless bins of unity width are chosen` . So in our usage, the sum doesn't become 1. We can see the trend of Histogram but Y-axis value itself is  useless
- I propose using the number of samples so that a viewer can see the meaningful value. Also, a viewer can judge if the graph is created with enough samples or not
None
- It's just my suggestion. Please give me your feedback if you think we should keep using `Probability`
- Only Y-axis changes
The PR reviewers …
=> chore(histogram): display number for Y-axis instead of probability

src/caret_analyze/infra/lttng/records_provider_lttng.py, src/test/infra/lttng/test_latency_definitions.py
This is modified PR for https://github.com/tier4/caret_analyze/pull/432 .
When communicaton has no data, graph are not drawn and error.
Modify there is no drawn but legend is displayed.
=> fix: error when drawn empty communication

src/caret_analyze/plot/visualize_lib/bokeh/callback_scheduling.py, src/caret_analyze/plot/visualize_lib/bokeh/message_flow.py, src/caret_analyze/plot/visualize_lib/bokeh/timeseries.py, src/caret_analyze/plot/visualize_lib/bokeh/util/util.py
Changed implementation so that BokehUserWarning (out of range integer) is not generated.
Converted time difference from UnixTime to Time Difference by subtracting offset before giving array to bokeh.
Jira: https://tier4.atlassian.net/browse/RT2-1071
Please check the following:
- implementation problem
- Are there any Warnings?
- Does the main and output match?
- pytest
=> fix: bokeh interger warning

src/caret_analyze/architecture/graph_search.py
Fixed argument error passed to _find_node_path
https://tier4.atlassian.net/browse/RT2-1190
=> fix: fixed argument error passed to _find_node_path

mkdocs-requirements.txt
- mkdocstrings v0.24.0 was released on 2023/11/14, but `deploy-docs` fails with this version.
- Failed session log : https://github.com/tier4/caret_analyze/actions/runs/6924178028
- Change log: https://mkdocstrings.github.io/changelog/#0240-2023-11-14
- As a workaround, CARET should avoid using v0.23.0
=> chore: mkdocstrings version to avoid 0.24

src/setup.py
Fixed the issue that `log_config.yaml` was not copied when using `colcon build` without `--symlink-install` option.
=> fix: log config is not copied after the build

src/caret_analyze/infra/lttng/lttng.py, src/caret_analyze/infra/lttng/lttng_event_filter.py
speeding up by limiting registration to init_events
https://tier4.atlassian.net/browse/RT2-1375
=> fix: speeding up by limiting registration to init_events

src/caret_analyze/__init__.py, src/caret_analyze/architecture/__init__.py, src/caret_analyze/architecture/architecture.py, src/caret_analyze/architecture/architecture_loaded.py, src/caret_analyze/architecture/util.py, src/test/architecture/test_architecture.py, src/test/architecture/test_architecture_loader.py
Restrict construction_order when searching for node callbacks paths.
[https://tier4.atlassian.net/browse/RT2-1261](https://tier4.atlassian.net/browse/RT2-1261)
=> fix: restrict max_construction_order at serch for node callbacks

src/caret_analyze/record/records_service/response_time.py, src/test/record/records_service/test_response_time_all.py
ignore data flow until first data of output column arrived in Response Time.
Jira: https://tier4.atlassian.net/browse/RT2-1430
=> feat: cut response times which have  first end timestamps

src/caret_analyze/common/type_check_decorator.py
code maintenance of `type_check_decorator` is conducted.
The changes are as follows:
- The annotation information can be getted by `get_annotations()` without get all `signature`. #[4283e74](https://github.com/tier4/caret_analyze/pull/489/commits/4283e74c1e98881b0e21fdd9060a9c49ec5d70bf)
- Simplify code by using `dict.get()` to get dict elements. #[4bded45](https://github.com/tier4/caret_analyze/pull/489/commits/4bded45b0e4d2d9924ea778513e357d39751d855)
- Variable-length arguments do not fall under `e.title==IterableArg`, so determine whether the argument is iterable without using `e.title`. #[0af9f5d](https://github.com/tier4/caret_analyze/pull/489/commits/0af9f5d391b1e8ed2ae9552316226b3317039fc6)
The PR author …
=> refactor: `type check decorator`

src/caret_analyze/common/summary.py, src/caret_analyze/infra/lttng/lttng.py
`abstractproperty` is deprecated.
Changed to `property` and `abstractmethod`.
=> refactor: abstractproperty is deprecated

src/caret_analyze/value_objects/node.py, src/test/value_objects/test_node_struct_value.py
Changed arguments for get_timer
https://tier4.atlassian.net/browse/RT2-1506
=> fix: changed arguments for get_timer

src/caret_analyze/infra/lttng/lttng.py
Fixed problem with ros2 caret check_ctf not validating even if a single path is entered
[Tier4 INTERNAL LINK](https://tier4.atlassian.net/browse/RT2-1595)
=> fix: fixed the feature to detect the number of trace data to be analyzed

src/caret_analyze/infra/lttng/event_counter.py, src/caret_analyze/infra/lttng/records_provider_lttng.py, src/caret_analyze/infra/lttng/records_source.py, src/caret_analyze/infra/lttng/ros2_tracing/data_model.py, src/caret_analyze/infra/lttng/ros2_tracing/data_model_service.py, src/caret_analyze/infra/lttng/ros2_tracing/processor.py, src/caret_analyze/runtime/path.py, src/test/infra/lttng/test_lttng.py, src/test/infra/lttng/test_records_provider_lttng.py, src/test/runtime/test_application.py, src/test/runtime/test_path.py
Adapted the implementation to support calling subscription->take at the intended timing to retrieve the message, rather than using subscription_callback. In this case, modified the code to merge records based on source_timestamp.
=> feat: merge using the source timestamp

src/caret_analyze/plot/visualize_lib/bokeh/util/hover.py
Use 'visible' instead of 'toggleable' since bokeh 3.4.0
[https://tier4.atlassian.net/browse/RT2-1763](https://tier4.atlassian.net/browse/RT2-1763)
=> fix: use visible instead of toggleable since bokeh 3.4.0

src/caret_analyze/plot/visualize_lib/bokeh/bokeh.py
Suppress the display of multiple hover icons when displaying histograms.
[https://tier4.atlassian.net/browse/RT2-1785](https://tier4.atlassian.net/browse/RT2-1785)
=> fix: set to 'visible=False' to HoverTool()

src/caret_analyze/plot/visualize_lib/bokeh/util/legend.py
Only one legend is displayed, despite the warning that the maximum number of legends (20) has been exceeded.
[https://tier4.atlassian.net/browse/RT2-1791](https://tier4.atlassian.net/browse/RT2-1791)
=> fix: updated legend count check

src/caret_analyze/common/type_check_decorator.py, src/test/common/test_type_check_decorator.py
Fixed type_check_decorator
https://tier4.atlassian.net/browse/RT2-1532
=> fix: fixed type_check_decorator

src/caret_analyze/architecture/architecture.py, src/requirements.txt
In mypy 1.11, untyped-overrides are now more strictly checked.
Fixing the problems pointed out and updating the ci mypy version.
- [TIERⅣ INTERNAL LINK](https://tier4.atlassian.net/browse/RT2-1752)
- [mypy/CHANGELOG.md at master · python/mypy](https://github.com/python/mypy/blob/master/CHANGELOG.md#stricter-checks-for-untyped-overrides)
=> fix: mypy1.11 error `untyped-overrides`

.github/workflows/pytest.yaml
On the current Docker image, python3-typeguard=2.2.2 is installed. Since this version causes inconsistencies, we are applying a temporary workaround to reinstall typeguard.
=> fix: temporary workaround for the issue where typeguard 2.2.2 is installed

src/caret_analyze/infra/lttng/lttng.py, src/caret_analyze/infra/lttng/lttng_info.py, src/caret_analyze/infra/lttng/records_provider_lttng.py, src/caret_analyze/infra/lttng/records_source.py
Fix docstring for method returning RecordsCppImpl and TracePointData
=> refactor: docstring for method returning RecordsCppImpl and TracePointData

mkdocs-requirements.txt
`tag:deploy_docs` is not work, because griffe>=1.0.0 and mkdocstring <=0.23 are not match.
Specified installed version of griffe.
=> fix: deploy docs has error because installed griffe>=1.0.0

src/caret_analyze/architecture/architecture.py, src/caret_analyze/architecture/architecture_loaded.py, src/caret_analyze/architecture/util.py
AssignContextReader is a class that inherits from ArchitectureReader, but it implements almost none of ArchitectureReader's functions, making the code difficult to understand.
Delete the AssignContextReader class and change the implementation to be more in line with the actual situation.
[https://tier4.atlassian.net/browse/RT2-1845](https://tier4.atlassian.net/browse/RT2-1845)
=> refactor: class to edit message_context

src/caret_analyze/infra/lttng/lttng.py, src/test/infra/lttng/test_latency_definitions.py
If there is no time MSG in the processing time of the target object, use all time MSGs to configure the sim_time converter
[https://tier4.atlassian.net/browse/RT2-1881](https://tier4.atlassian.net/browse/RT2-1881)
In caret_report, no warning messages or other logs from caret_analyze are displayed.
=> fix: configuration sim_time converter

src/requirements.txt
Add the setuptools version specification to requirements.txt.
[https://tier4.atlassian.net/browse/RT2-1858](https://tier4.atlassian.net/browse/RT2-1858)
If setuptools is already installed with privileges, you may need to run sudo pip uninstall setuptools multiple times to install the version specified in requirements.txt.
=> fix: setuptools version specification to requirements.txt

src/caret_analyze/infra/lttng/records_provider_lttng.py, src/caret_analyze/runtime/path.py, src/test/infra/lttng/test_latency_definitions.py, src/test/runtime/test_path.py
Modify the following two points
* If all callback_start_timestamp columns are empty in the Communication just before take implementation, remove them.
* rmw_take with topic name qualification.
[https://tier4.atlassian.net/browse/RT2-1838](https://tier4.atlassian.net/browse/RT2-1838)
=> fix: subscription take

src/requirements.txt
Revert the setuptools version specification back to the previous setuptools>=68.2.2.
[https://tier4.atlassian.net/browse/RT2-1951](https://tier4.atlassian.net/browse/RT2-1951)
=> fix: setuptools version

src/test/test_flake8.py
Exclude struct/__init__.py from test_frake8.py.
[https://tier4.atlassian.net/browse/RT2-1985](https://tier4.atlassian.net/browse/RT2-1985)
=> fix: exclude "struct/__init__.py" from test_frake8.py

src/caret_analyze/infra/lttng/event_counter.py
Use default value if no key is registered in `event_counter.py`
=> fix: use default value if no key registration

src/caret_analyze/infra/trace_point_data.py, src/caret_analyze/record/interface.py
Modification of methods that have been disabled since multimethod version 2.
- [TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/RT2-2080)
- document for `multimethod`
- https://coady.github.io/multimethod/#multimethod
=> fix: modified methods for multimethod v2.

src/caret_analyze/infra/lttng/records_provider_lttng.py, src/caret_analyze/runtime/path.py, src/test/infra/lttng/test_latency_definitions.py, src/test/infra/lttng/test_records_provider_lttng.py, src/test/runtime/test_path.py
Fixed merge method for nodes that get messages by take() on user code.
- [TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/RT2-2081)
=> fix: fixed merge timestamp_key for nodes that get messages by take() on user code

src/caret_analyze/plot/visualize_lib/bokeh/timeseries.py
An error occurs when multiple types of input are given to create_frequency_timeseries_plot().
https://tier4.atlassian.net/browse/RT2-2126
=> fix: error occurs when multiple types of input are given to create frequency timeseries plot

src/requirements.txt
bokeh 3.7.0 has been released, but type checking does not pass in the python 3.10 environment. For this reason, the installation of 3.7.0 is excluded.
[https://tier4.atlassian.net/browse/RT2-2235](https://tier4.atlassian.net/browse/RT2-2235)
=> fix: exclude 3.7.0 from bokeh installation

src/caret_analyze/architecture/architecture_loaded.py, src/caret_analyze/runtime/path.py, src/package.xml, src/test/architecture/test_architecture_loader.py
logger.warn() will be deprecated and cause warning message.
Therefore it has been replaced with logger.warning()
I run `pytest-3 test` and confirmed that the following messages disappeared.
```
src/test/architecture/test_architecture_loader.py::TestSubscriptionsLoaded::test_duplicated_subscription_name
/home/takahisaishikawa/caret_ws/ros2_caret_ws/src/CARET/caret_analyze/src/caret_analyze/architecture/architecture_loaded.py:836: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
logger.warn(e)
```
=> refactor: replace logger.warn() to logger.warning()

src/requirements.txt
The github release of bokeh 3.7.0 fixes a function problem with type hints in python 3.10. On the other hand, it turns out that the pip-installed bokeh 3.7.0 and 3.7.1 still have the type hinting problem. We will temporarily remove support for bokeh 3.7 and later versions until we can confirm that the problem has been resolved.
- https://github.com/tier4/caret_analyze/pull/556
=> chore: exclude bokeh 3.7 to avoid type hint problems

src/caret_analyze/record/records_service/frequency.py
This PR simplifies the frequency calculation logic by using numpy.
Testing was done by running the existing test suite.
```
~/caret_ws/ros2_caret_ws/src/CARET/caret_analyze/src$ pytest-3 test/record/records_service/test_frequency.py -s
```
For all unit test, there is only 1 failure related to flake8 test. But they are not warnings for `frequency.py`
```
~/caret_ws/ros2_caret_ws/src/CARET/caret_analyze/src$ pytest-3 test
```
=> refactor: frequency calculation logic

src/caret_analyze/plot/timeseries/frequency_timeseries.py, src/test/plot/timeseries/test_frequency_timeseries.py
- Added test for plot/timeseries/frequency_timeseriers.py
- Added function to calculate frequency with timestamp offset.
Frequency is computed over each 1-second interval.
If the data frequency is around 1Hz, computing it without an offset can lead to unstable results.
For instance, if the time difference between consecutive data points is slightly less or more than 1 second (e.g., 999ms or 1001ms), a fixed 1-second window might capture a variable number of data points. This can cause the computed frequency to fluctuate (e.g., alternating between 0Hz and 2Hz) even if the true data frequency is stable.
This explains why the plotting result looks unstable, as shown in the following figure.
Therefore, as a countermeasure, I have added an offset to the start time of the frequency computation …
=> feat: calculate frequency computing offset

src/caret_analyze/plot/timeseries/frequency_timeseries.py, src/caret_analyze/record/records_service/frequency.py, src/test/plot/timeseries/test_frequency_timeseries.py
- Added calculation end time to trim the last sampling period.
- Refactored frequency plotting test
- Fixed missing end time limitation in frequency calculation.
Previously, the final segment of the frequency calculation often contained incomplete data. This occurred because the recording's finish time was not synchronized with the defined calculation period boundaries. As a result, the frequency plot would show a sudden drop at the very end, as illustrated in the figure below:
With this change, only time intervals with complete data samples are used for the calculation period. This leads to a more stable and accurate frequency plot:
In the scenario where `start_ns` > `end_ns`, the frequency is calculated as 0 Hz without triggering an error.
The PR reviewers **must** check the checkboxes …
=> feat: improve accuracy of frequency calculation period determination

.github/workflows/pytest.yaml
In pytest.yaml, rosdep is installed but fails due to PGP key expiration. 
Because of this, pytest could not run. The rosdep
[https://tier4.atlassian.net/browse/RT0-38358](https://tier4.atlassian.net/browse/RT0-38358)
=> fix: unable to run pytest in github actions
